import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="pb-5">
        Main content here...
      </main>

      <footer>
        Footer here...
      </footer>
    </div>
  )
}
